### ISSUE TITLE
Inconsistent focus on map behavior.

### ISSUE THREAD

**Issue by caoliver** [pekwm/pekwm#128] opened 2022-03-14 18:50 UTC
Focus on new window mapping seems very inconsistent.  I quite often type a hot key to get an xterm to type a few commands, but whether or not the new window receives focus on mapping seems to have something to do with its placement and the current cursor position.  I really don't have much of a clue here.  See the following video which I made with a fresh github clone (same behavior as my build from a while ago):  https://youtu.be/UNLI65jgikA

**Comment by pekdon** [comment] 2022-03-21 12:08
Closing as duplicate of #10

**Closed by pekdon** 2022-03-21 12:08 UTC
Labels: duplicate
